<a href="https://colab.research.google.com/github/deriiinjv/pytorch-playground/blob/main/pytorch-1(rev).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch numpy --quiet


In [2]:
import torch

In [3]:
##Tensors
t1=torch.tensor(4.)
t1
t1.dtype

torch.float32

In [9]:
##vector
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [11]:
##matrix
t3=torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
##3d dimensional array
t4=torch.tensor([[[11,12,13],[13,14,15],[15,16,17],[17,18,19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.],
         [15., 16., 17.],
         [17., 18., 19.]]])

In [12]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [15]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [16]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [17]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.],
         [15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([1, 4, 3])

**Tensor operations and gradients**

In [18]:
#create tensors
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [19]:
##arithmetic operations
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [20]:
##compute derivatives
y.backward()

In [21]:
#Display gradients
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


**Interoperability with Numpy**

In [22]:
import numpy as np
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [23]:
# numpy to torch tensor
y=torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [24]:
x.dtype,y.dtype

(dtype('int64'), torch.int64)

In [25]:
##torch tensor to numpy
z=y.numpy()
z

array([[1, 2],
       [3, 4]])